# -*- coding: utf-8 -*-
"""Data Visualisation using Matplotlib.ipynb

Automatically generated by Colaboratory.


# Load Pandas Library
import pandas as pd
import numpy as np

#Creating DataFrame and Loading csv file
df = pd.read_csv('/content/sample_data/placement.csv')
df

#Data Visualization
#Line Chart, Bar Chart, Histogram, Scatter plot

import matplotlib.pyplot as plt

# x=df['Name'].head(5)
# y=df['SSC (%)'].head(5)
# plt.plot(x,y)
# plt.title('Cumulative UG Score')
# plt.xlabel('Student Name')
# plt.ylabel('Graduation')
# plt.show()


df1 = df.head(10)
ax = plt.gca()
df1.plot(kind='line', x='Name', y='SSC (%)', color='blue', ax=ax)
df1.plot(kind='line', x='Name', y='HSC (%)', color='red', ax=ax)
df1.plot(kind='line', x='Name', y='Graduation', color='black', ax=ax)
plt.show()

# df.plot(kind='scatter', x='SSC (%)', y='HSC (%)', color='blue')
# plt.title('Scatter Graph')
# plt.xlabel("X-axis")
# plt.ylabel("Y-axis")
# plt.show()

x1 = [89, 43, 36, 36, 95, 10,
      66, 34, 38, 20]
 
y1 = [21, 46, 3, 35, 67, 95,
      53, 72, 58, 10]
 
# dataset2
x2 = [26, 29, 48, 64, 6, 5,
      36, 66, 72, 40]
 
y2 = [26, 34, 90, 33, 38,
      20, 56, 2, 47, 15]
 
plt.scatter(x1, y1, c ="pink",
            linewidths = 2,
            marker ="s",
            edgecolor ="green",
            s = 50)
 
plt.scatter(x2, y2, c ="yellow",
            linewidths = 2,
            marker ="^",
            edgecolor ="red",
            s = 200)
 
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()

# Horizontal Bar Plot
# section = df['Name'].head(5)
# marks = df['HSC (%)'].head(5)
# plt.bar(section, marks, color='blue')
# plt.title('Bar Graph')
# plt.show()

#Histogram
df['Graduation'].hist()

#Creating Subplots
import numpy as np
import matplotlib.pyplot as plt
#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot()
plt.subplot(1, 2, 1)
plt.plot(x,y)

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(1, 2, 2)
plt.plot(x,y)

plt.show()