# -*- coding: utf-8 -*-
"""Data Visualisation using Seaborn.ipynb

Automatically generated by Colaboratory.



# Load Pandas Library
import pandas as pd
import numpy as n
import seaborn as sns

#Creating DataFrame and Loading csv file
df = pd.read_csv('/content/sample_data/placement.csv')
df

#Data Visualization using Seaborn
#Line Plot
#sns.lineplot( df['HSC (%)'], df['Graduation'])

#Scatter Plot
#sns.scatterplot(df['HSC (%)'], df['Graduation'],hue =df["Course"])

#Bar Plot
#sns.barplot(df['HSC (%)'].head(5), df['Graduation'].head(5))

#Historgram
#sns.distplot(df['Graduation'].head(10))
#sns.distplot(df['Graduation'].head(30),kde=False,bins=10)

#Box Plot
sns.boxplot( df['Graduation'].head(20))

#Violin Plot
#sns.violinplot(df['HSC (%)'].head(10))

#Swarm Plot
#sns.swarmplot(df['HSC (%)'].head(30), df['Graduation'].head(30))

#Point Plot
#sns.pointplot(df['HSC (%)'].head(10), df['Graduation'].head(10))

#Count Plot - used to show count of observations in each categorical bin using bars.
#sns.countplot(df['M/F'])

#KDE Plot
#sns.kdeplot( df['HSC (%)'].head(10), df['Graduation'].head(10))